# Site settings
title: Acusp's Blog
SEOTitle: 岐点 | Acusp's Blog
header-img: img/home-bg.jpg
email: acusp.xu@gmail.com
description: "about programming, linux, security."
keyword: ""
url: "http://acusp.info"
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: true
weibo_username:     acusp
zhihu_username:     acusp
github_username:    acusp
#twitter_username:  acusp
#facebook_username:  huxpro



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: acusp
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing



# Analytics settings
# Baidu Analytics
ba_track_id: ce472038c53a64826054bafc870d2d24
# Google Analytics
ga_track_id: 'UA-96564187-1'
ga_domain: acusp.info



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "各种好奇，各种分享，新技能Get"
sidebar-avatar: /img/avatar-hux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Misky Blog",
        href: "http://misky.info"
    },{
        title: "Foo",
        href: "#"
    },{
        title: "Bar",
        href: "#"
    },{
        title: "Example Friends",
        href: "#"
    }
]
